# Generated by Django 3.1.1 on 2020-10-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melody', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='songImage',
            field=models.ImageField(blank=True, null=True, upload_to='songImages/'),
        ),
    ]
