# Generated by Django 3.1.1 on 2020-10-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melody', '0002_song_coverphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profilepicture',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
