# Generated by Django 3.1.1 on 2020-10-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melody', '0003_customer_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='coverphoto',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
