# Generated by Django 3.1.1 on 2020-10-11 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('melody', '0004_auto_20201012_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='coverphoto',
        ),
    ]
