# Generated by Django 3.1.1 on 2020-10-11 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('melody', '0002_song_songimage'),
        ('melody', '0005_remove_song_coverphoto'),
    ]

    operations = [
    ]
