# Generated by Django 3.1.1 on 2020-10-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melody', '0006_merge_20201012_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='songImage',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
